# Generated by Django 3.2.9 on 2021-11-04 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='note_created',
            new_name='timestamp',
        ),
    ]
